### ISSUE TITLE
[BUG]: Double restart

### ISSUE THREAD

**Issue by GhostFRR** [PerformanC/ReZygisk#90] opened 2024-11-23 12:01 UTC
### Version

V1.0.0 rc1

### Modules

ReZygisk by The PerformanC Organization version v1.0.0 rc1 

### Description

Hello, I've noticed what seems to be a bug because when I restart my phone with RE Zygisk turned on my phone performs a first boot and a few seconds later, it restarts again. At this point I can finally connect. And once connected, YouTube and YT Musicale disappear, as does Reddit patch with revancedextended. My phone is running under custom ROM (LineagOS 21 on Pixel 7 Pro).

Ps: When I run with native magisk's Zygisk i dont have the issue 

Thanks !

### Steps to reproduce

Just restart phone 😅 

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment] 2024-11-23 13:46
Can you join our Discord? I need to send different builds with file-backed logging

**Comment by JingMatrix** [comment] 2024-11-23 19:51
Bug confirmed, it is due to some incompatibility with my LSPosed:
```
11-23 20:34:49.257  3140  3140 V LSPosedService: binder org.lsposed.lspd.service.LSPosedService@13d367f
11-23 20:34:49.257  3140  3140 E Parcel  : Recycle called on unowned Parcel. (recycle twice?) Here: java.lang.Throwable
11-23 20:34:49.257  3140  3140 E Parcel  : 	at android.os.Parcel.recycle(Parcel.java:596)
11-23 20:34:49.257  3140  3140 E Parcel  : 	at org.lsposed.lspd.service.BridgeService.sendToBridge(BridgeService.java:148)
11-23 20:34:49.257  3140  3140 E Parcel  : 	at org.lsposed.lspd.service.BridgeService.send(BridgeService.java:179)
11-23 20:34:49.257  3140  3140 E Parcel  : 	at org.lsposed.lspd.service.ServiceManager.start(ServiceManager.java:158)
11-23 20:34:49.257  3140  3140 E Parcel  : 	at org.lsposed.lspd.Main.main(Main.java:8)
11-23 20:34:49.257  3140  3140 E Parcel  : 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-23 20:34:49.257  3140  3140 E Parcel  : 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
11-23 20:34:49.257  3140  3140 E Parcel  :  Original recycle call (if DEBUG_RECYCLE): 
11-23 20:34:49.258  3140  3140 E AndroidRuntime: Error reporting WTF
11-23 20:34:49.258  3140  3140 E AndroidRuntime: java.lang.RuntimeException: Unknown exception code: -2147483648 msg null
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3218)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3198)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3140)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at android.os.IServiceManager$Stub$Proxy.checkService(IServiceManager.java:506)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at android.os.ServiceManagerProxy.checkService(ServiceManagerNative.java:73)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService2(ServiceManagerNative.java:69)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at android.os.ServiceManager.rawGetService(ServiceManager.java:428)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:175)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at android.app.ActivityManager$4.create(ActivityManager.java:5835)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at android.app.ActivityManager$4.create(ActivityManager.java:5832)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:44)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at android.app.ActivityManager.getService(ActivityManager.java:5823)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.wtf(RuntimeInit.java:439)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at android.util.Log$1.onTerribleFailure(Log.java:135)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at android.util.Log.wtf(Log.java:343)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at android.util.Log.wtf(Log.java:332)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at android.os.Parcel.recycle(Parcel.java:596)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at org.lsposed.lspd.service.BridgeService.sendToBridge(BridgeService.java:148)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at org.lsposed.lspd.service.BridgeService.send(BridgeService.java:179)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at org.lsposed.lspd.service.ServiceManager.start(ServiceManager.java:158)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at org.lsposed.lspd.Main.main(Main.java:8)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
11-23 20:34:49.258  3140  3140 E AndroidRuntime: LSPosed
11-23 20:34:49.258  3140  3140 E AndroidRuntime: Original WTF:
11-23 20:34:49.258  3140  3140 E AndroidRuntime: android.util.Log$TerribleFailure: Recycle called on unowned Parcel. (recycle twice?) Here: java.lang.Throwable
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at android.os.Parcel.recycle(Parcel.java:596)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at org.lsposed.lspd.service.BridgeService.sendToBridge(BridgeService.java:148)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at org.lsposed.lspd.service.BridgeService.send(BridgeService.java:179)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at org.lsposed.lspd.service.ServiceManager.start(ServiceManager.java:158)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at org.lsposed.lspd.Main.main(Main.java:8)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
11-23 20:34:49.258  3140  3140 E AndroidRuntime:  Original recycle call (if DEBUG_RECYCLE): 
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at android.util.Log.wtf(Log.java:338)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at android.util.Log.wtf(Log.java:332)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at android.os.Parcel.recycle(Parcel.java:596)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at org.lsposed.lspd.service.BridgeService.sendToBridge(BridgeService.java:148)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at org.lsposed.lspd.service.BridgeService.send(BridgeService.java:179)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at org.lsposed.lspd.service.ServiceManager.start(ServiceManager.java:158)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at org.lsposed.lspd.Main.main(Main.java:8)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-23 20:34:49.258  3140  3140 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
11-23 20:34:49.258  3140  3140 E Parcel  : Recycle called on unowned Parcel. (recycle twice?) Here: java.lang.Throwable
11-23 20:34:49.258  3140  3140 E Parcel  : 	at android.os.Parcel.recycle(Parcel.java:596)
11-23 20:34:49.258  3140  3140 E Parcel  : 	at org.lsposed.lspd.service.BridgeService.sendToBridge(BridgeService.java:149)
11-23 20:34:49.258  3140  3140 E Parcel  : 	at org.lsposed.lspd.service.BridgeService.send(BridgeService.java:179)
11-23 20:34:49.258  3140  3140 E Parcel  : 	at org.lsposed.lspd.service.ServiceManager.start(ServiceManager.java:158)
11-23 20:34:49.258  3140  3140 E Parcel  : 	at org.lsposed.lspd.Main.main(Main.java:8)
11-23 20:34:49.258  3140  3140 E Parcel  : 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-23 20:34:49.258  3140  3140 E Parcel  : 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
11-23 20:34:49.258  3140  3140 E Parcel  :  Original recycle call (if DEBUG_RECYCLE): 
```

**Comment by GhostFRR** [comment] 2024-11-23 20:01
Since installing Kernel SU, I don't seem to have any more double reboot problems !

Previously I used Magisk 27

**Comment by JingMatrix** [comment] 2024-11-23 20:14
I have hear bugs report as this one: https://github.com/JingMatrix/LSPosed/issues/62, which used a WIP version of ReZygisk.
Now the revelant commits have been merged into the main branch, I thus suggest @ThePedroo to figure out the problematic commits.

**Comment by JingMatrix** [comment] 2024-11-23 20:47
> Since installing Kernel SU, I don't seem to have any more double reboot problems !
> 
> Previously I used Magisk 27

Correct, with KernelSU, the issue disappears.

**Comment by JingMatrix** [comment] 2024-11-23 22:19
You can close this issue now, I have fixed in the LSPosed part.
Current behavior of LSPosed with ReZygisk on Magisk is acceptable.

**Comment by ThePedroo** [comment] 2024-11-23 22:21
Awesome!

**Closed by ThePedroo** 2024-11-23 22:21 UTC
Labels: bug, confirmed
